version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    stdin_open: true
    restart: on-failure
    container_name: client
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: server
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container